# server port
server:
  port: 8082

# application 명
spring:
  application:
    name: work
    
# zipkin base 설정
  zipkin:
    base-url: http://127.0.0.1:9411/ 
    enabled: true

# slueth 설정
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

# zipkin sample
sample:
  zipkin:
    enabled: true

# logging level for org.springframework.web
logging:
  level:
    org:
      springframework:
        web: DEBUG